### ISSUE TITLE
Multiplicar dos fracciones

### ISSUE THREAD

**Issue by ghost** [ilagev/SpaiEcp2IvanLage#2]
Método que recibe una fracción por parámetro y se multiplica por ella.

Más información en la [wiki](https://github.com/ilagev/SpaiEcp2IvanLage/wiki/F%232---Multiplicar-dos-fracciones).

**Comment by ghost** [comment]
Hola Jennifer,

Cuando vayas a ponerte con esta mejora, si ya te bajaste el proyecto, por favor haz antes `Fetch from Upstream` antes de ponerte con la mejora, ya que en la rama develop he actualizando el fichero `pom.xml` por un problema con el Travis.

Gracias de antemano, saludos ;)

**Comment by JenniferGarciaDeLaCalle** [comment]
Mejora realizada
