### ISSUE TITLE
Fracción menor que otra

### ISSUE THREAD

**Issue by ghost** [ilagev/SpaiEcp2IvanLage#3]
Método que comprueba si una fracción es menor que otra recibida por parámetro.

Más información en la [wiki](https://github.com/ilagev/SpaiEcp2IvanLage/wiki/F%233---Fracci%C3%B3n-menor-que-otra).

**Comment by fer2d2** [comment]
Hola Iván,

Añado los cambios en este punto. Los tests no pasan, ni en local ni en Travis. Cuando puedas revísalo, pues yo no tengo otra forma de saber si remotamente mi proyecto _funciona_ o no.

https://travis-ci.org/ilagev/SpaiEcp2IvanLage

El error tiene que ver con el pom.xml

```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'modelVersion' must be one of [4.0.0] but is '1.0.0'. @ line 5, column 16
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project es.upm.miw:SpaiEcp2IvanLage:0.0.1-SNAPSHOT (/home/ferthedems/Escritorio/MIW/SpaiEcp2IvanLage/pom.xml) has 1 error
[ERROR]     'modelVersion' must be one of [4.0.0] but is '1.0.0'. @ line 5, column 16
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

¡Un saludo!

**Comment by fer2d2** [comment]
Cierro el issue a falta de que lo reabras en caso de que algo falle.

**Comment by ghost** [comment]
Ya está arreglado. En efecto tenías razón, el problema estaba en el pom.xml. Al cambiar la versión a 4.0.0 (que era el valor que esperaba) funciona bien Travis. Le había cambiado la versión a a 1.0.0 al principio nada más crear el proyecto (antes de subirlo a git), pero por alguna razón esto no le gustó. Bueno, de todo se aprende :)

He integrado la rama `ModifyPOM` en `develop`, que ya incluye tanto el cambio de versión como las 3 mejoras que acabas de hacer.

Muchas gracias por avisar Fernando :) cierro tus tres issues.

Voy a comentar en las issues abiertas que hagan fetch antes de ponerse con las mejoras.

Saludos
