### ISSUE TITLE
Modificar coordenadas

### ISSUE THREAD

**Issue by ghost** [ilagev/SpaiEcp2IvanLage#4]
Método que actualiza las coordenadas a valores pasados por parámetro.

Más información en la [wiki](https://github.com/ilagev/SpaiEcp2IvanLage/wiki/F%234---Modificar-coordenadas).

**Comment by fer2d2** [comment]
Actualizado. Cuando se corrija el problema de los tests por el `pom.xml`, se puede cerrar.

**Comment by ghost** [comment]
Problema arreglado, muchas gracias. Cierro ticket.
