### ISSUE TITLE
Está en diagonal principal

### ISSUE THREAD

**Issue by ghost** [ilagev/SpaiEcp2IvanLage#5]
Método que indica si un punto se encuentra en la diagonal principal.

Más información en la [wiki](https://github.com/ilagev/SpaiEcp2IvanLage/wiki/F%235---Est%C3%A1-en-diagonal-principal).

**Comment by ghost** [comment]
Hola Jennifer,

Cuando vayas a ponerte con esta mejora, si ya te bajaste el proyecto, por favor haz antes `Fetch from Upstream` antes de ponerte con la mejora, ya que en la rama develop he actualizando el fichero `pom.xml` por un problema con el Travis.

Gracias de antemano, saludos ;)

**Comment by JenniferGarciaDeLaCalle** [comment]
Mejora realizada
