### ISSUE TITLE
Añadir edad

### ISSUE THREAD

**Issue by ghost** [ilagev/SpaiEcp2IvanLage#7]
Añadir un nuevo atributo a la clase User que indique su edad, con métodos de lectura y escritura.

Más información en la [wiki](https://github.com/ilagev/SpaiEcp2IvanLage/wiki/F%237---A%C3%B1adir-edad).

**Comment by ghost** [comment]
Hola Jennifer,

Cuando vayas a ponerte con esta mejora, si ya te bajaste el proyecto, por favor haz antes `Fetch from Upstream` antes de ponerte con la mejora, ya que en la rama develop he actualizando el fichero `pom.xml` por un problema con el Travis.

Gracias de antemano, saludos ;)

**Comment by JenniferGarciaDeLaCalle** [comment]
Mejora realizada.
