### ISSUE TITLE
Multiplicar números

### ISSUE THREAD

**Issue by ghost** [ilagev/SpaiEcp2IvanLage#8]
Método que multiplica todos los números de la lista de DecimalCollection por un número pasado por parámetro.

Más información en la [wiki](https://github.com/ilagev/SpaiEcp2IvanLage/wiki/F%238---Multiplicar).

**Comment by ghost** [comment]
Hola Adrián,

Cuando vayas a ponerte con esta mejora, por favor haz antes `Fetch from Upstream` antes de ponerte con la mejora, ya que en la rama develop he actualizando el fichero `pom.xml` por un problema con el Travis.

Gracias de antemano, saludos ;)

**Comment by McAdri** [comment]
Mejora añadida
