### ISSUE TITLE
Existe número

### ISSUE THREAD

**Issue by ghost** [ilagev/SpaiEcp2IvanLage#9]
Método que comprueba si un valor está en la lista de DecimalCollection.

Más información en la [wiki](https://github.com/ilagev/SpaiEcp2IvanLage/wiki/F%239---Existe-n%C3%BAmero).

**Comment by fer2d2** [comment]
Actualizado. Cuando se corrija el problema de los tests por el `pom.xml`, se puede cerrar.

**Comment by ghost** [comment]
Problema arreglado, muchas gracias. Cierro ticket.
